spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    schema:
      file-extensions:
        - .graphqls
        - .gqls
        - .graphql
  elasticsearch:
    uris: elasticsearch:9200
    username: elastic
    password: elastic
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:features}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

app:
  validation: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - env
          - info
          - beans
          - caches
          - configprops
          - loggers
          - mappings
          - metrics
          - prometheus
          - threaddump
          - scheduledtasks
          - logfile
          - startup
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
    prometheus:
      enabled: true
    caches:
      enabled: true