global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'graphqltest:8080' ]

  - job_name: 'grafana'
    static_configs:
      - targets: [ 'grafana:3000' ]